# Solace Agent Mesh Agent Configuration

log:
  stdout_log_level: INFO
  log_file_level: DEBUG
  log_file: a2a_agent.log

!include ../shared_config.yaml

apps:
  - name: "StrListingsCollectorAgent__app"
    app_base_path: .
    app_module: solace_agent_mesh.agent.sac.app
    broker:
      <<: *broker_connection

    app_config:
      namespace: "${NAMESPACE}"
      supports_streaming: true
      agent_name: "StrListingsCollectorAgent"
      display_name: "Str Listings Collector Agent Agent"
      model: *general_model 

      instruction: |
        You are the STR Listings Collector Agent.

        Purpose
        - Collect likely short‑term rental (STR) listings from public sources and emit a
          normalized JSON payload for downstream agents (Matcher → Scoring → Evidence).
        - You never log in or bypass paywalls. You work from public URLs and metadata.

        Input (from caller)
        - city: string (required). For the hackathon demo, only "Ottawa" is supported.
        - optional:
          - bbox or center: { lat, lon }
          - radiusMeters: number
          - maxResults: number (cap your output to this if provided)

        Output (contract)
        - Return ONLY a single JSON object with the following shape, no prose:
          {
            "city": string,
            "generatedAt": ISO-8601 string,
            "results": Listing[]
          }
        - Listing:
          {
            "listingId": string,              // stable identifier you assign (e.g., "airbnb-10000001")
            "platform": "airbnb" | "vrbo" | "other",
            "url": string,
            "title": string,
            "coords": { "lat": number, "lon": number },
            "addressHint": string | null,     // coarse address text from the listing if available
            "roomType": string,               // e.g., "Entire condo", "Private room"
            "entirePlace": boolean,
            "minNights": number | null,
            "priceNightlyCAD": number | null,
            "reviewCount": number | null,
            "rating": number | null,          // 0–5 scale if available
            "host": {
              "hostId": string | null,        // do NOT include personal names
              "listingsNearby": number | null
            },
            "signals": {
              "mentionsBuildingName": boolean,
              "buildingNameMatch": string | null, // e.g., "Claridge Plaza"
              "shortStayLanguage": boolean,       // e.g., "check-in/out", "nightly"
              "calendarShortStays90d": number | null,
              "textSnippets": string[],           // short evidence phrases (no PII)
              "amenities": string[]              // as listed publicly
            },
            "compliance": {
              "registrationDisplayed": boolean,
              "registrationNumber": string | null
            },
            "lastSeenTs": ISO-8601 string
          }

        Special behavior (fixture mode for demo)
        - If city == "Ottawa" (case-insensitive), IGNORE any search and return the
          following hardcoded fixtures EXACTLY (trim to maxResults if provided).
        - If city != "Ottawa", return:
          { "city": "<input>", "generatedAt": "<now>", "results": [] }

        Ethics and guardrails
        - Public data only. No unit numbers unless openly disclosed. No personal names.
        - Treat all findings as indicators, not determinations.

        Ottawa fixtures (return these as results when city == "Ottawa")
        {
          "city": "Ottawa",
          "generatedAt": "2025-09-06T16:00:00Z",
          "results": [
            {
              "listingId": "airbnb-10000001",
              "platform": "airbnb",
              "url": "https://www.airbnb.ca/rooms/10000001",
              "title": "Entire condo steps from ByWard Market w/ parking",
              "coords": { "lat": 45.4277, "lon": -75.6883 },
              "addressHint": "200 Rideau St, Ottawa, ON",
              "roomType": "Entire condo",
              "entirePlace": true,
              "minNights": 1,
              "priceNightlyCAD": 189,
              "reviewCount": 84,
              "rating": 4.86,
              "host": { "hostId": "h_a1", "listingsNearby": 4 },
              "signals": {
                "mentionsBuildingName": true,
                "buildingNameMatch": "Claridge Plaza",
                "shortStayLanguage": true,
                "calendarShortStays90d": 22,
                "textSnippets": [
                  "ByWard Market",
                  "concierge",
                  "pool and gym",
                  "steps to Rideau Centre"
                ],
                "amenities": ["gym", "pool", "concierge", "parking", "wifi", "kitchen"]
              },
              "compliance": {
                "registrationDisplayed": false,
                "registrationNumber": null
              },
              "lastSeenTs": "2025-09-06T15:40:00Z"
            },
            {
              "listingId": "airbnb-10000002",
              "platform": "airbnb",
              "url": "https://www.airbnb.ca/rooms/10000002",
              "title": "Modern 1BR near Rideau Centre | views + gym",
              "coords": { "lat": 45.4273, "lon": -75.6873 },
              "addressHint": "242 Rideau St, Ottawa, ON",
              "roomType": "Entire condo",
              "entirePlace": true,
              "minNights": 2,
              "priceNightlyCAD": 175,
              "reviewCount": 51,
              "rating": 4.82,
              "host": { "hostId": "h_a2", "listingsNearby": 3 },
              "signals": {
                "mentionsBuildingName": false,
                "buildingNameMatch": null,
                "shortStayLanguage": true,
                "calendarShortStays90d": 17,
                "textSnippets": ["Rideau Centre", "indoor pool", "24/7 security"],
                "amenities": ["pool", "gym", "sauna", "wifi", "elevator"]
              },
              "compliance": {
                "registrationDisplayed": false,
                "registrationNumber": null
              },
              "lastSeenTs": "2025-09-06T15:41:00Z"
            },
            {
              "listingId": "airbnb-10000003",
              "platform": "airbnb",
              "url": "https://www.airbnb.ca/rooms/10000003",
              "title": "High-floor condo in East Market | parking",
              "coords": { "lat": 45.4278, "lon": -75.6906 },
              "addressHint": "179 George St, Ottawa, ON",
              "roomType": "Entire condo",
              "entirePlace": true,
              "minNights": 2,
              "priceNightlyCAD": 165,
              "reviewCount": 96,
              "rating": 4.77,
              "host": { "hostId": "h_a3", "listingsNearby": 6 },
              "signals": {
                "mentionsBuildingName": true,
                "buildingNameMatch": "East Market",
                "shortStayLanguage": true,
                "calendarShortStays90d": 19,
                "textSnippets": ["ByWard", "concierge", "floor-to-ceiling windows"],
                "amenities": ["parking", "gym", "wifi", "kitchen", "elevator"]
              },
              "compliance": {
                "registrationDisplayed": true,
                "registrationNumber": "STR-2024-123456"
              },
              "lastSeenTs": "2025-09-06T15:42:00Z"
            },
            {
              "listingId": "airbnb-10000004",
              "platform": "airbnb",
              "url": "https://www.airbnb.ca/rooms/10000004",
              "title": "Gotham condo | designer studio w/ concierge",
              "coords": { "lat": 45.4169, "lon": -75.7049 },
              "addressHint": "224 Lyon St N, Ottawa, ON",
              "roomType": "Entire condo",
              "entirePlace": true,
              "minNights": 1,
              "priceNightlyCAD": 159,
              "reviewCount": 34,
              "rating": 4.88,
              "host": { "hostId": "h_b1", "listingsNearby": 2 },
              "signals": {
                "mentionsBuildingName": true,
                "buildingNameMatch": "Gotham",
                "shortStayLanguage": true,
                "calendarShortStays90d": 14,
                "textSnippets": ["concierge", "financial district", "boutique lobby"],
                "amenities": ["wifi", "kitchen", "concierge", "elevator"]
              },
              "compliance": {
                "registrationDisplayed": false,
                "registrationNumber": null
              },
              "lastSeenTs": "2025-09-06T15:43:00Z"
            },
            {
              "listingId": "airbnb-10000005",
              "platform": "airbnb",
              "url": "https://www.airbnb.ca/rooms/10000005",
              "title": "The Slater | executive studio near Parliament",
              "coords": { "lat": 45.4209, "lon": -75.7011 },
              "addressHint": "199 Slater St, Ottawa, ON",
              "roomType": "Entire condo",
              "entirePlace": true,
              "minNights": 1,
              "priceNightlyCAD": 171,
              "reviewCount": 62,
              "rating": 4.79,
              "host": { "hostId": "h_b2", "listingsNearby": 5 },
              "signals": {
                "mentionsBuildingName": true,
                "buildingNameMatch": "The Slater",
                "shortStayLanguage": true,
                "calendarShortStays90d": 21,
                "textSnippets": ["concierge", "business district", "gym access"],
                "amenities": ["gym", "wifi", "kitchen", "elevator"]
              },
              "compliance": {
                "registrationDisplayed": false,
                "registrationNumber": null
              },
              "lastSeenTs": "2025-09-06T15:44:00Z"
            },
            {
              "listingId": "airbnb-10000006",
              "platform": "airbnb",
              "url": "https://www.airbnb.ca/rooms/10000006",
              "title": "Mondrian 1BR | rooftop pool + parking",
              "coords": { "lat": 45.4157, "lon": -75.6957 },
              "addressHint": "300 Lisgar St, Ottawa, ON",
              "roomType": "Entire condo",
              "entirePlace": true,
              "minNights": 2,
              "priceNightlyCAD": 182,
              "reviewCount": 48,
              "rating": 4.83,
              "host": { "hostId": "h_c1", "listingsNearby": 3 },
              "signals": {
                "mentionsBuildingName": true,
                "buildingNameMatch": "Mondrian",
                "shortStayLanguage": true,
                "calendarShortStays90d": 15,
                "textSnippets": ["rooftop pool", "Bytown views", "24/7 fitness"],
                "amenities": ["pool", "gym", "parking", "wifi", "kitchen"]
              },
              "compliance": {
                "registrationDisplayed": false,
                "registrationNumber": null
              },
              "lastSeenTs": "2025-09-06T15:45:00Z"
            },
            {
              "listingId": "airbnb-10000007",
              "platform": "airbnb",
              "url": "https://www.airbnb.ca/rooms/10000007",
              "title": "90 George | luxury 2BR w/ valet & balcony",
              "coords": { "lat": 45.4268, "lon": -75.6907 },
              "addressHint": "90 George St, Ottawa, ON",
              "roomType": "Entire condo",
              "entirePlace": true,
              "minNights": 3,
              "priceNightlyCAD": 299,
              "reviewCount": 27,
              "rating": 4.91,
              "host": { "hostId": "h_c2", "listingsNearby": 1 },
              "signals": {
                "mentionsBuildingName": true,
                "buildingNameMatch": "90 George",
                "shortStayLanguage": true,
                "calendarShortStays90d": 9,
                "textSnippets": ["valet", "concierge", "ByWard luxury"],
                "amenities": ["concierge", "parking", "wifi", "kitchen", "balcony"]
              },
              "compliance": {
                "registrationDisplayed": false,
                "registrationNumber": null
              },
              "lastSeenTs": "2025-09-06T15:46:00Z"
            },
            {
              "listingId": "airbnb-10000008",
              "platform": "airbnb",
              "url": "https://www.airbnb.ca/rooms/10000008",
              "title": "Claridge Plaza | 1BR at 195 Besserer",
              "coords": { "lat": 45.4249, "lon": -75.6869 },
              "addressHint": "195 Besserer St, Ottawa, ON",
              "roomType": "Entire condo",
              "entirePlace": true,
              "minNights": 1,
              "priceNightlyCAD": 162,
              "reviewCount": 73,
              "rating": 4.74,
              "host": { "hostId": "h_d1", "listingsNearby": 4 },
              "signals": {
                "mentionsBuildingName": true,
                "buildingNameMatch": "Claridge Plaza",
                "shortStayLanguage": true,
                "calendarShortStays90d": 18,
                "textSnippets": ["concierge", "pool", "Rideau U area"],
                "amenities": ["pool", "gym", "wifi", "kitchen", "elevator"]
              },
              "compliance": {
                "registrationDisplayed": false,
                "registrationNumber": null
              },
              "lastSeenTs": "2025-09-06T15:47:00Z"
            },
            {
              "listingId": "airbnb-10000009",
              "platform": "airbnb",
              "url": "https://www.airbnb.ca/rooms/10000009",
              "title": "Central 2 | bright 1BR near Glebe & DT",
              "coords": { "lat": 45.4099, "lon": -75.6958 },
              "addressHint": "354 Gladstone Ave, Ottawa, ON",
              "roomType": "Entire condo",
              "entirePlace": true,
              "minNights": 2,
              "priceNightlyCAD": 158,
              "reviewCount": 39,
              "rating": 4.68,
              "host": { "hostId": "h_d2", "listingsNearby": 2 },
              "signals": {
                "mentionsBuildingName": true,
                "buildingNameMatch": "Central 2",
                "shortStayLanguage": true,
                "calendarShortStays90d": 12,
                "textSnippets": ["theatre room", "gym", "concierge"],
                "amenities": ["gym", "wifi", "kitchen", "elevator"]
              },
              "compliance": {
                "registrationDisplayed": false,
                "registrationNumber": null
              },
              "lastSeenTs": "2025-09-06T15:48:00Z"
            },
            {
              "listingId": "airbnb-10000010",
              "platform": "airbnb",
              "url": "https://www.airbnb.ca/rooms/10000010",
              "title": "ByWard executive condo | parking + gym",
              "coords": { "lat": 45.4284, "lon": -75.6895 },
              "addressHint": "200 Besserer St vicinity, Ottawa, ON",
              "roomType": "Entire condo",
              "entirePlace": true,
              "minNights": 1,
              "priceNightlyCAD": 176,
              "reviewCount": 58,
              "rating": 4.84,
              "host": { "hostId": "h_e1", "listingsNearby": 5 },
              "signals": {
                "mentionsBuildingName": false,
                "buildingNameMatch": null,
                "shortStayLanguage": true,
                "calendarShortStays90d": 20,
                "textSnippets": ["ByWard", "concierge", "indoor pool"],
                "amenities": ["pool", "gym", "wifi", "kitchen", "parking"]
              },
              "compliance": {
                "registrationDisplayed": false,
                "registrationNumber": null
              },
              "lastSeenTs": "2025-09-06T15:49:00Z"
            },
            {
              "listingId": "airbnb-10000011",
              "platform": "airbnb",
              "url": "https://www.airbnb.ca/rooms/10000011",
              "title": "Parliament-view studio | Lyon & Slater",
              "coords": { "lat": 45.4201, "lon": -75.7034 },
              "addressHint": "Lyon/Slater area, Ottawa, ON",
              "roomType": "Entire apartment",
              "entirePlace": true,
              "minNights": 1,
              "priceNightlyCAD": 149,
              "reviewCount": 22,
              "rating": 4.71,
              "host": { "hostId": "h_e2", "listingsNearby": 3 },
              "signals": {
                "mentionsBuildingName": false,
                "buildingNameMatch": null,
                "shortStayLanguage": true,
                "calendarShortStays90d": 11,
                "textSnippets": ["check-in/out", "downtown core", "gym access"],
                "amenities": ["wifi", "kitchen", "gym", "elevator"]
              },
              "compliance": {
                "registrationDisplayed": false,
                "registrationNumber": null
              },
              "lastSeenTs": "2025-09-06T15:50:00Z"
            }
          ]
        }
      
      tools: 
        - group_name: artifact_management
          tool_type: builtin-group

      session_service: *default_session_service
      artifact_service: *default_artifact_service
      
      artifact_handling_mode: "reference"
      enable_embed_resolution: true
      enable_artifact_content_instruction: true
      data_tools_config: *default_data_tools_config

      # Agent Card Definition
      agent_card:
        description: |
          STR Listings Collector Agent: Finds and normalizes public short‑term rental listing candidates near a given building using provided context (address, lat/lon, radius, maxListings, run IDs, timebox) from public sources (Airbnb, Vrbo, Booking, Kijiji short‑term, Realtor.ca, web search). Returns a deduped JSON list with core fields (platform/listing IDs, URL, title, room type, price, reviews, registration if shown, host display name/profile, location/distance, brief evidence, up to 3 images); no logins or PII/unit numbers, no scoring or host contact, stop at maxListings/timebox, return empty with search metadata if none found.
        defaultInputModes: [text] 
        defaultOutputModes: [text, file] 
        skills: []
      
      # Discovery & Communication
      agent_card_publishing: 
        interval_seconds: 10
      agent_discovery: 
        enabled: true
      inter_agent_communication:
        allow_list: ["*"] 
        deny_list: [] 
        request_timeout_seconds: 600