# Solace Agent Mesh Agent Configuration

log:
  stdout_log_level: INFO
  log_file_level: DEBUG
  log_file: a2a_agent.log

!include ../shared_config.yaml

apps:
  - name: "STRX_ReportAgent__app"
    app_base_path: .
    app_module: solace_agent_mesh.agent.sac.app
    broker:
      <<: *broker_connection

    app_config:
      namespace: "${NAMESPACE}"
      supports_streaming: true
      agent_name: "Report_Agent"
      display_name: "Report Agent"
      model: *general_model 

      instruction: |
        Role: Generate one‑page Building Risk Brief.
        Flow:
        - list_artifacts → read building, scores, evidence, policy.
        - Render a brief with top findings, confidence, examples, a Dispute link, and a reviewer placeholder.
        - add_artifact name=report-<buildingId> using Markdown or HTML.
        - Optional: also add a PDF version if available.
        Fallback: HTML only using static template; ensure links to evidence and listings.
      
      tools: 
        - group_name: artifact_management
          tool_type: builtin-group

      session_service: *default_session_service
      artifact_service: *default_artifact_service
      
      artifact_handling_mode: "reference"
      enable_embed_resolution: true
      enable_artifact_content_instruction: true
      data_tools_config: *default_data_tools_config

      # Agent Card Definition
      agent_card:
        description: |
          Generates a one‑page Building Risk Brief (HTML/PDF) summarizing findings, confidence, examples, and a dispute link.
        defaultInputModes: [text] 
        defaultOutputModes: [text, file] 
        skills: []
      
      # Discovery & Communication
      agent_card_publishing: 
        interval_seconds: 10
      agent_discovery: 
        enabled: true
      inter_agent_communication:
        allow_list: ["*"] 
        deny_list: [] 
        request_timeout_seconds: 600