# Solace Agent Mesh Agent Configuration

log:
  stdout_log_level: INFO
  log_file_level: DEBUG
  log_file: a2a_agent.log

!include ../shared_config.yaml

apps:
  - name: "STRX_STRListingsCollectorAgent__app"
    app_base_path: .
    app_module: solace_agent_mesh.agent.sac.app
    broker:
      <<: *broker_connection

    app_config:
      namespace: "${NAMESPACE}"
      supports_streaming: true
      agent_name: "STR_Listings_Collector"
      display_name: "STR Listings Collector"
      model: *general_model 

      instruction: |
        Role: Produce public STR listings.
        Flow:
        - list_artifacts → if listings-<city> exists, stop.
        - Else use Brightdata MCP (if available) to fetch; else create Ottawa fixtures.
        - add_artifact name=listings-<city> including fields: city; generatedAt timestamp; results list of listings. Use any suitable format; Markdown or structured text is fine.
        - Keep fixture small (10–12 items), privacy‑safe, deterministic.
      
      tools: 
        - group_name: artifact_management
          tool_type: builtin-group
        - tool_type: mcp
          connection_params:
            type: stdio
            command: "npx"
            args:
              - "-y"
              - "mcp-remote"
              - "https://mcp.brightdata.com/sse?token=${BRIGHTDATA_TOKEN}&pro=1"

      session_service: *default_session_service
      artifact_service: *default_artifact_service
      
      artifact_handling_mode: "reference"
      enable_embed_resolution: false
      enable_artifact_content_instruction: true
      data_tools_config: *default_data_tools_config

      # Agent Card Definition
      agent_card:
        description: |
          Gathers public short‑term rental listings and outputs a normalized dataset for downstream agents.
        defaultInputModes: [text] 
        defaultOutputModes: [text, file] 
        skills: []
      
      # Discovery & Communication
      agent_card_publishing: 
        interval_seconds: 10
      agent_discovery: 
        enabled: true
      inter_agent_communication:
        allow_list: ["*"] 
        deny_list: [] 
        request_timeout_seconds: 600