# Solace Agent Mesh Agent Configuration

log:
  stdout_log_level: INFO
  log_file_level: DEBUG
  log_file: a2a_agent.log

!include ../shared_config.yaml

apps:
  - name: "STRX_ScoringAgent__app"
    app_base_path: .
    app_module: solace_agent_mesh.agent.sac.app
    broker:
      <<: *broker_connection

    app_config:
      namespace: "${NAMESPACE}"
      supports_streaming: true
      agent_name: "Scoring_Agent"
      display_name: "Scoring Agent"
      model: *general_model 

      instruction: |
        Role: Score STR likelihood.
        Flow:
        - list_artifacts → read matches-<buildingId>.json and listings.
        - Apply heuristics: +20 near or inside; +20 building name match; +15 entire place; +10 reviews at least 20; +10 short‑stay language; +10 host with at least 3 listings nearby; +10 no registration present; minus 25 if registration displayed; minus 15 if minimum nights at least 30.
        - Tiers: 70 or more is high; 40–69 is medium; otherwise low.
        - add_artifact name=scores-<buildingId> including fields: buildingId and a scored list; format is flexible.
      
      tools: 
        - group_name: artifact_management
          tool_type: builtin-group

      session_service: *default_session_service
      artifact_service: *default_artifact_service
      
      artifact_handling_mode: "reference"
      enable_embed_resolution: true
      enable_artifact_content_instruction: true
      data_tools_config: *default_data_tools_config

      # Agent Card Definition
      agent_card:
        description: |
          Assigns an explainable 0–100 likelihood score and confidence tier to each matched listing.
        defaultInputModes: [text] 
        defaultOutputModes: [text, file] 
        skills: []
      
      # Discovery & Communication
      agent_card_publishing: 
        interval_seconds: 10
      agent_discovery: 
        enabled: true
      inter_agent_communication:
        allow_list: ["*"] 
        deny_list: [] 
        request_timeout_seconds: 600